// Rules documentation: https://palantir.github.io/tslint/rules/
module.exports = {
  extends: `tslint:recommended`,
  defaultSeverity: `error`,
  rules: {
    'array-type': [true, `array-simple`],
    'arrow-parens': false,
    'arrow-return-shorthand': true,
    'ban-types': [false, `Function`],
    'import-spacing': true,
    'indent': [true, `spaces`],
    'interface-name': false,
    'max-line-length': [true, 140],
    'no-angle-bracket-type-assertion': false,
    'no-conditional-assignment': true,
    'no-consecutive-blank-lines': [true, 1],
    'no-console': false,
    'no-duplicate-variable': true,
    'no-invalid-template-strings': true,
    'no-namespace': [true, `allow-declarations`],
    'object-literal-sort-keys': false,
    'only-arrow-functions': false,
    'quotemark': [true, `single`, `avoid-escape`],
    'semicolon': [true, `always`],
    'switch-default': true,
  },
};
